/**
 * @file    main.c
 * @brief   Basic STM32 application that blinks an LED and periodically sends "hi\r\n" over UART4.
 *
 * This program:
 *  - Configures the system clock to use HSI (no PLL).
 *  - Initializes GPIO for an LED (push-pull) and a user button interrupt (rising edge).
 *  - Initializes UART4 at 115200-8N1, no flow control.
 *  - Toggles LED every 500 ms.
 *  - Transmits "hi\r\n" every 1000 ms on UART4 (blocking transmit with 100 ms timeout).
 *
 * Dependencies:
 *  - STM32 HAL drivers.
 *  - Board support defines for pins/ports such as LED_GREEN_GPIO_Port, LED_GREEN_Pin, etc.
 *
 * @note
 *  Ensure that USART4 pins are correctly routed to the appropriate GPIO alternate function
 *  for your board, and that the LED and button pins match your hardware.
 */

#include "main.h"      // Project-specific HAL/board header (GPIO, UART handles, pin mappings)
#include <string.h>    // For strlen

/** @brief Period for UART transmit in milliseconds. */
#define UART_TX_PERIOD_MS   (1000U)
/** @brief Timeout for HAL_UART_Transmit in milliseconds. */
#define UART_TIMEOUT_MS     (100U)

/** @brief Global UART handle for USART4. */
UART_HandleTypeDef huart4;

/** @brief Tick timestamp of the last LED toggle (ms). */
uint32_t lastBlink = 0;

/** @brief Constant TX message payload. */
static const char kMsg[] = "hi\r\n";

/**
 * @brief  Configure system clock: HSI ON, no PLL, SYSCLK = HSI, AHB=1, APB1=1.
 *
 * This sets:
 *  - Voltage scaling to Range 1 (for higher performance).
 *  - HSI ON with default calibration, no division.
 *  - No PLL.
 *  - SYSCLK source = HSI.
 *  - FLASH latency = 0 (suitable for low SYSCLK).
 *
 * @retval None. On failure, calls Error_Handler().
 */
void SystemClock_Config(void) {
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};  // Zero-init oscillator config structure
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};  // Zero-init clock tree config structure

  HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1); // Set voltage scaling to Range 1

  // --- Oscillator configuration: HSI on, no PLL ---
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;     // Use HSI oscillator
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;                       // Turn HSI on
  RCC_OscInitStruct.HSIDiv = RCC_HSI_DIV1;                       // No HSI division
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT; // Default trim
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;                 // Disable PLL
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
    Error_Handler();                 // Trap on failure
  }

  // --- Clock tree configuration: SYSCLK from HSI, AHB=1, APB1=1 ---
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK      // Configure AHB
                               | RCC_CLOCKTYPE_SYSCLK   // Configure SYSCLK
                               | RCC_CLOCKTYPE_PCLK1;   // Configure APB1
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;    // SYSCLK = HSI
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;        // HCLK = SYSCLK/1
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;         // PCLK1 = HCLK/1
  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK) {
    Error_Handler();                 // Trap on failure
  }
}

/**
 * @brief  Initialize GPIO for:
 *         - User button (B1) as rising-edge interrupt, no pull.
 *         - USART2 TX/RX alternate function (AF1) on GPIOA (if used by BSP).
 *         - LED (LED_GREEN) as push-pull output, high speed, no pull.
 *
 * @note Modify pin names/ports to match your board definitions in main.h / CubeMX.
 *
 * @retval None
 */
static void MX_GPIO_Init(void) {
  GPIO_InitTypeDef GPIO_InitStruct = {0};  // Zero-init GPIO config structure

  // --- Enable GPIO port clocks (as required by used pins) ---
  __HAL_RCC_GPIOC_CLK_ENABLE();  // Enable GPIOC clock (e.g., for B1)
  __HAL_RCC_GPIOF_CLK_ENABLE();  // Enable GPIOF clock (if used)
  __HAL_RCC_GPIOA_CLK_ENABLE();  // Enable GPIOA clock (LED/USART pins)

  // --- Set initial LED state to LOW (off) ---
  HAL_GPIO_WritePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin, GPIO_PIN_RESET);

  // --- Configure User Button B1: rising-edge interrupt, no pull ---
  GPIO_InitStruct.Pin = B1_Pin;                 // Button pin
  GPIO_InitStruct.Mode = GPIO_MODE_IT_RISING;   // Interrupt on rising edge
  GPIO_InitStruct.Pull = GPIO_NOPULL;           // No pull-up/down
  HAL_GPIO_Init(B1_GPIO_Port, &GPIO_InitStruct);

  // --- Configure USART2 TX/RX pins on GPIOA (AF1) ---
  // Note: These are typically generated by CubeMX; keep if you use USART2.
  GPIO_InitStruct.Pin = USART2_TX_Pin | USART2_RX_Pin; // TX and RX pins
  GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;              // Alternate function push-pull
  GPIO_InitStruct.Pull = GPIO_NOPULL;                  // No pull-up/down
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;         // Low speed is sufficient for AF
  GPIO_InitStruct.Alternate = GPIO_AF1_USART2;         // AF mapping for USART2
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

  // --- Configure LED pin as output (push-pull), high speed ---
  GPIO_InitStruct.Pin = LED_GREEN_Pin;           // LED pin
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;    // Push-pull output
  GPIO_InitStruct.Pull = GPIO_NOPULL;            // No pull
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;  // High speed for crisp toggles
  HAL_GPIO_Init(LED_GREEN_GPIO_Port, &GPIO_InitStruct);
}

/**
 * @brief  Initialize UART4 with 115200-8N1, no flow control, oversampling x16.
 *
 * Configuration:
 *  - BaudRate       : 115200
 *  - WordLength     : 8 bits
 *  - StopBits       : 1
 *  - Parity         : None
 *  - Mode           : TX/RX
 *  - HwFlowCtl      : None
 *  - OverSampling   : 16
 *  - OneBitSampling : Disabled
 *  - ClockPrescaler : DIV1
 *
 * @retval None. On failure, calls Error_Handler().
 */
static void MX_USART4_UART_Init(void) {
  huart4.Instance = USART4;                               // Select UART4 peripheral
  huart4.Init.BaudRate = 115200;                          // 115200 bps
  huart4.Init.WordLength = UART_WORDLENGTH_8B;            // 8 data bits
  huart4.Init.StopBits = UART_STOPBITS_1;                 // 1 stop bit
  huart4.Init.Parity = UART_PARITY_NONE;                  // No parity
  huart4.Init.Mode = UART_MODE_TX_RX;                     // Enable TX and RX
  huart4.Init.HwFlowCtl = UART_HWCONTROL_NONE;            // No RTS/CTS
  huart4.Init.OverSampling = UART_OVERSAMPLING_16;        // Oversampling by 16
  huart4.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE; // Disable 1-bit sampling
  huart4.Init.ClockPrescaler = UART_PRESCALER_DIV1;       // No prescaling
  huart4.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT; // No advanced features

  if (HAL_UART_Init(&huart4) != HAL_OK) {
    Error_Handler();                                      // Trap on failure
  }
}

/**
 * @brief  Periodic LED toggle task driven by HAL_GetTick() timestamp.
 *
 * @param  now        Current time in ms (HAL_GetTick()).
 * @param  pLastBlink Pointer to last toggle timestamp (modified on toggle).
 * @note   Toggles LED on PA5 every 500 ms. Adjust GPIO as per your board.
 */
static inline void LedToggleTask(uint32_t now, uint32_t *pLastBlink) {
  // Check if 500 ms have elapsed since the last toggle
  if ((uint32_t)(now - *pLastBlink) >= 500U) {
    HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);  // Toggle LED on PA5
    *pLastBlink = now;                      // Update last toggle time
  }
}

/**
 * @brief  Application entry point.
 *
 * Initializes HAL, system clock, GPIO, and UART4; enters main loop that:
 *  - Toggles LED every 500 ms (non-blocking check).
 *  - Sends "hi\r\n" over UART4 every 1000 ms (blocking transmit with 100 ms timeout).
 *
 * @retval int Not used; function never returns.
 */
int main(void) {
  HAL_Init();                 // Initialize HAL library and SysTick
  SystemClock_Config();       // Configure system clocks
  MX_GPIO_Init();             // Initialize GPIO (LED, button, USART2 pins)
  MX_USART4_UART_Init();      // Initialize UART4 (115200-8N1)

  // --- Superloop ---
  while (1) {
    uint32_t now = HAL_GetTick();                                  // Get current tick in ms
    LedToggleTask(now, &lastBlink);                                 // Toggle LED if due

    // Send "hi\r\n" over UART4 (blocking, with timeout)
    HAL_UART_Transmit(&huart4, (uint8_t*)kMsg, (uint16_t)strlen(kMsg), UART_TIMEOUT_MS);

    HAL_Delay(UART_TX_PERIOD_MS);                                   // Wait 1000 ms
  }
}

/**
 * @brief  Error handler: disables IRQs and loops forever.
 *
 * Use for irrecoverable errors; consider adding LED blink patterns or
 * a safe reset strategy for production systems.
 */
void Error_Handler(void) {
  __disable_irq();   // Globally disable interrupts
  while (1) {
    // Stay here; optionally add error indication (e.g., LED blink)
  }
}

#ifdef USE_FULL_ASSERT
/**
 * @brief  Reports the name of the source file and line number where the assert_param error has occurred.
 * @param  file: pointer to the source file name
 * @param  line: assert_param error line source number
 * @retval None
 */
void assert_failed(uint8_t *file, uint32_t line)
{
  (void)file; (void)line;   // Suppress unused parameter warnings
  // Optionally send file/line over UART or store for debugging
}
#endif
